# rules.mk

VIA_ENABLE = yes 
OLED_ENABLE = yes 
OLED_DRIVER = ssd1306 
OLED_TRANSPORT = i2c 

BOOTMAGIC_ENABLE = yes

ENCODER_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
WS2812_DRIVER_REQUIRED = yes

QMK_C_DEFS += -DKEYBOARD_USER_ENABLE

LTO_ENABLE = yes 