# rules.mk

VIA_ENABLE = yes 
OLED_ENABLE = yes 
OLED_DRIVER = ssd1306 
OLED_TRANSPORT = i2c 

BOOTMAGIC_ENABLE = yes

HAPTIC_ENABLE = yes 
HAPTIC_DRIVER = solenoid 

QMK_C_DEFS += -DKEYBOARD_USER_ENABLE

LTO_ENABLE = yes 