# rules.mk

VIA_ENABLE = yes 
OLED_ENABLE = yes 
OLED_DRIVER = ssd1306 
OLED_TRANSPORT = i2c 

BOOTMAGIC_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
RGBLIGHT_DRIVER = ws2812_pio
WS2812_BITBANG = no
WS2812_DRIVER_REQUIRED = yes

QMK_C_DEFS += -DKEYBOARD_USER_ENABLE

LTO_ENABLE = yes 